project_name: 'VehicleDetection'
experiment_name: 'raw'
n_epochs: 1
accelerator: 'gpu'
device: 0
monitor_metric: 'val_total_loss'
monitor_mode: 'min'

model: 'src.efficientdet.backbone.EfficientDetBackbone'
model_kwargs:
  compound_coef: 0
  input_sizes: [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]


optimizer: 'torch.optim.AdamW'
optimizer_kwargs: {}

scheduler: 'torch.optim.lr_scheduler.ReduceLROnPlateau'
scheduler_kwargs:
  mode: 'min'
  patience: 3
  verbose: true

loss: 'src.efficientdet.loss.FocalLoss'
loss_kwargs: {}

data_config:
  data_path: '/detector/datasets/birdview_vehicles'
  train_set: 'train'
  val_set: 'val'
  n_workers: 2
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]
  anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
  anchors_ratios: '[(0.7, 1.4), (1.0, 1.0), (1.5, 0.7)]'
  obj_list: ['large-vehicle', 'small-vehicle']
  collate_fn: 'efficientdet.dataset.collater'
  training_params:
    batch_size: 4
    shuffle: true
    drop_last: true
    num_workers: 2
  val_params:
    batch_size: 4
    shuffle: false
    drop_last: true
    num_workers: 2
